server:
  port: 5000

spring:
  application:
    name: "vehicle-guide"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/vehicleguide"
    hikari:
      auto-commit: true
      username: "root"
      password: "root"
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
