server:
  port: 5000

spring:
  application:
    name: "vehicle-guide"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://dev-vehicleguide.cfsprt6kxrun.eu-west-1.rds.amazonaws.com:3306/vehicleguide"
    hikari:
      auto-commit: true
      username: "miluna"
      password: "vehicleguidepass"
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
